Добавляет наставника
htmlacademy-htmlcss/407173-sedona-33 pull request #1
Opened 2022-01-18 17:18 UTC by Yu-hub-yu

2022-01-18 21:00 UTC, Ankhena requested changes

2022-01-18 21:00 UTC, Ankhena commented on Readme.md
> +* Наставник: `Анна Лисененкова`.
Давай посмотрим, что получилось в результате
https://github.com/Yu-hub-yu/407173-sedona-33

Вроде бы данные единообразные, а выглядят совсем по-разному.
Было бы лучше, если бы у наставника тоже была ссылка и такой же вид текста, как и у студентки.
![2022-01-18_23-56-13](https://user-images.githubusercontent.com/20879307/150017750-73fb3083-0740-4af8-b6d2-0e26b152b2b8.jpg)

2022-01-18 21:00 UTC, Ankhena commented on Readme.md
Написала в ВК

2022-01-19 03:27 UTC, Yu-hub-yu commented on Readme.md
> +* Наставник: `Анна Лисененкова`.
Привет, Анна! я добавила ссылку

2022-01-19 08:01 UTC, merged